### PR TITLE
Web transactions support

### PR DESCRIPTION
**Pull request by milankinen**
Modify ring wrapper so that it uses `NewRelic.setRequestResponse(...)` and produces web transaction to the NewRelic's control panel instead of "non-web" transaction.

Modified core so that it supports web transaction creation.

### CODE REVIEW

**Comment by pupeno** [comment]
@mlank did you release a jar with proper web transaction support? I want to have that but if you made a release I'll skip doing one myself.

**Comment by mlank** [comment]
@pupeno This pull request is under review (in Yleisradio) and once it's completed, it'll be merged into master and published to Clojars (will happen during the next few days).

**Comment by pupeno** [comment]
@mlank I understand that, but in the meantime, it can be released as a jar with another groupId so that we can start using it. If you haven't done it, I'll do it myself, as I need this code in a server and I don't know of a better way. Do you have a better way?

**Comment by mlank** [comment]
I don't think it's wise to create a "temporary" groupId just for getting the jar one day before the "actual release" (well probably release a new version tomorrow). Are you that hurry that you can't wait one day?

**Comment by pupeno** [comment]
@mlank I am actually in kind of a hurry as I need to move on to other things. If this wasn't implementing I would be implementing it myself. I will request the jar to be remove once the next version of new-reliquary is released, I am aware the confusion this may cause.

As a plus, I can comment that this feature is working well for me. Thank you @mlank for implementing it.

**Comment by mlank** [comment]
@pupeno You're welcome. Of course it works, I implemented it. ;-) Unfortunately I don't have the sufficient credentials right here to publish this pull request today so I guess it's up to you to decide how to handle this case.

**Pull request merged**
