### PR TITLE
Use parametrized Compojure request URI if possible. & Add an option to add the HTTP method to the New Relic transaction name.

### PR DESCRIPTION
**Pull request by sluukkonen**
Not sure what the option name should be . `:add-method-to-transaction-name` might be a bit too long.

### CODE REVIEW

**Comment by mlank** [comment]
:+1:

**Comment by mlank** [comment]
@sluukkonen Looks great! Could you add notes about `:compojure/route` and `:add-method-to-transaction-name` to the README ring section? After that I don't see any reasons not to merge this into `master`.

**Comment by sluukkonen** [comment]
I just noticed that the [Compojure code](https://github.com/weavejester/compojure/pull/141) that makes this PR possible hasn't been released yet. So I'll put this PR on hold until Compojure gets a new release.

**Comment by rymndhng** [comment]
Bump on this, now that the PR has been merged into Compojure.

**Pull request closed without merging**
